import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { Check, Copy, RefreshCw, Smartphone } from "lucide-react";

type MobileConfig = { configured: boolean; inbox_id?: string; worker_url?: string; pages_url?: string; created_at?: string; pairing_url?: string };
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, init); const text = await response.text(); if (!response.ok) { try { throw new Error((JSON.parse(text) as { error?: string }).error || text); } catch (error) { if (error instanceof SyntaxError) throw new Error(text); throw error; } } return JSON.parse(text) as T; }

export function MobileSyncSettings({ onImported }: { onImported?: () => Promise<void> }) {
  const [config, setConfig] = useState<MobileConfig | null>(null); const [workerUrl, setWorkerUrl] = useState(""); const [pagesUrl, setPagesUrl] = useState(""); const [qr, setQr] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const next = await request<MobileConfig>("/api/mobile/config"); setConfig(next); if (next.worker_url) setWorkerUrl(next.worker_url); if (next.pages_url) setPagesUrl(next.pages_url); if (next.pairing_url) setQr(await QRCode.toDataURL(next.pairing_url, { width: 260, margin: 2, color: { dark: "#17282c", light: "#ffffff" } })); };
  useEffect(() => { void load(); }, []);
  const setup = async () => { setBusy(true); setMessage(""); try { await request("/api/mobile/config", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ worker_url: workerUrl, pages_url: pagesUrl }) }); setMessage("Mobile inbox created. Scan the QR code with your phone."); await load(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const sync = async () => { setBusy(true); try { const result = await request<{ imported: number }>("/api/mobile/sync", { method: "POST" }); if (result.imported) await onImported?.(); setMessage(result.imported ? `Imported ${result.imported} mobile capture${result.imported === 1 ? "" : "s"}.` : "No new mobile captures."); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };

  return <section className="mobile-sync-settings"><div className="ai-settings-head"><div><span className="eyebrow"><Smartphone size={16} />Mobile capture</span><h2>Capture ideas from Android</h2><p>Optional, self-hosted, end-to-end encrypted, and compatible with Android’s Share menu.</p></div>{config?.configured && <button className="secondary-button" disabled={busy} onClick={() => void sync()}><RefreshCw size={15} />Sync now</button>}</div>
    {!config?.configured ? <div className="mobile-setup-form"><label>Cloudflare Worker URL<input value={workerUrl} placeholder="https://your-worker.workers.dev" onChange={(event) => setWorkerUrl(event.target.value)} /></label><label>Cloudflare Pages URL<input value={pagesUrl} placeholder="https://your-project.pages.dev" onChange={(event) => setPagesUrl(event.target.value)} /></label><button className="primary-button" disabled={busy || !workerUrl.startsWith("https://") || !pagesUrl.startsWith("https://")} onClick={() => void setup()}>{busy ? "Creating…" : "Create encrypted mobile inbox"}</button></div> : <div className="pairing-panel"><div className="pairing-qr">{qr && <img src={qr} alt="Recall mobile pairing QR code" />}</div><div><h3>Pair your phone</h3><ol><li>Open your self-hosted Recall Pages URL.</li><li>Scan this QR code using the phone camera.</li><li>Install Recall from the browser menu.</li><li>In Google Keep, use Share → Recall.</li></ol><button className="secondary-button" onClick={() => void navigator.clipboard.writeText(config.pairing_url || "")}><Copy size={15} />Copy pairing link</button><p><Check />Pending captures are encrypted and removed from the relay after desktop import.</p></div></div>}{message && <p className={`form-message ${/created|imported|No new/i.test(message) ? "success" : "error"}`}>{message}</p>}
  </section>;
}
