import { useEffect, useState } from "react";
import { BookOpen, BrainCircuit, Check, Cloud, CloudOff, Folder, Lightbulb, Mic, Plus, RefreshCw, Search, Send, Settings, Share2, Smartphone, Sparkles, Tags } from "lucide-react";

interface Pairing { inboxId: string; key: string; token: string; workerUrl: string }
interface Capture { id: string; content: string; topic: string; project: string; created_at: string; iv: string; ciphertext: string; uploaded: boolean }
interface MobileMemory { id: string; content: string; topic?: string; category?: string; priority?: string; status?: string; workflow_status?: string; project?: string; created_at: string }
interface MemorySnapshot { version: number; generated_at: string; memories: MobileMemory[] }

const DB_NAME = "recall-mobile"; const DB_VERSION = 1;
function database(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, DB_VERSION); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains("settings")) db.createObjectStore("settings"); if (!db.objectStoreNames.contains("captures")) db.createObjectStore("captures", { keyPath: "id" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function getSetting<T>(key: string): Promise<T | null> { const db = await database(); return new Promise((resolve, reject) => { const request = db.transaction("settings").objectStore("settings").get(key); request.onsuccess = () => resolve(request.result ?? null); request.onerror = () => reject(request.error); }); }
async function setSetting(key: string, value: unknown): Promise<void> { const db = await database(); await new Promise<void>((resolve, reject) => { const tx = db.transaction("settings", "readwrite"); tx.objectStore("settings").put(value, key); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }
async function putCapture(capture: Capture): Promise<void> { const db = await database(); await new Promise<void>((resolve, reject) => { const tx = db.transaction("captures", "readwrite"); tx.objectStore("captures").put(capture); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }
async function listCaptures(): Promise<Capture[]> { const db = await database(); return new Promise((resolve, reject) => { const request = db.transaction("captures").objectStore("captures").getAll(); request.onsuccess = () => resolve((request.result as Capture[]).sort((a, b) => b.created_at.localeCompare(a.created_at))); request.onerror = () => reject(request.error); }); }

export function MobileApp() {
  const [pairing, setPairingState] = useState<Pairing | null>(null); const [captures, setCaptures] = useState<Capture[]>([]); const [memories, setMemories] = useState<MobileMemory[]>([]); const [view, setView] = useState<"capture" | "memories">("capture"); const [groupBy, setGroupBy] = useState<"topic" | "project">("topic"); const [search, setSearch] = useState(""); const [content, setContent] = useState(""); const [topic, setTopic] = useState(""); const [project, setProject] = useState(""); const [status, setStatus] = useState(""); const [online, setOnline] = useState(navigator.onLine); const [listening, setListening] = useState(false); const [refreshing, setRefreshing] = useState(false);
  useEffect(() => { void initialize(); const update = () => setOnline(navigator.onLine); window.addEventListener("online", update); window.addEventListener("offline", update); if ("serviceWorker" in navigator) void navigator.serviceWorker.register("/sw.js"); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); }; }, []);
  useEffect(() => { if (online && pairing) void sync(pairing); }, [online, pairing]);

  const initialize = async () => {
    const query = new URLSearchParams(location.search); const fragment = new URLSearchParams(location.hash.replace(/^#/, "")); const inbox = query.get("inbox"); const key = fragment.get("key"); const token = fragment.get("token"); let activePairing: Pairing | null;
    if (inbox && key && token) { const workerUrl = import.meta.env.VITE_SYNC_API_URL as string; activePairing = { inboxId: inbox, key, token, workerUrl }; await setSetting("pairing", activePairing); setPairingState(activePairing); history.replaceState({}, "", "/"); setStatus("Phone paired with desktop Recall."); }
    else { activePairing = await getSetting<Pairing>("pairing"); setPairingState(activePairing); }
    const shareText = [query.get("title"), query.get("text"), query.get("url")].filter(Boolean).join("\n"); if (shareText) { setContent(shareText); history.replaceState({}, "", "/"); }
    setCaptures(await listCaptures()); const cached = await getSetting<MemorySnapshot>("snapshot"); if (cached) setMemories(cached.memories); if (activePairing && navigator.onLine) await loadSnapshot(activePairing, false);
  };
  const save = async () => { if (!content.trim()) return; if (!pairing) { setStatus("Pair this phone from desktop Recall first."); return; } const payload = { id: crypto.randomUUID(), content: content.trim(), topic: topic.trim(), project: project.trim(), created_at: new Date().toISOString() }; const encrypted = await encrypt(payload, pairing.key); const capture: Capture = { ...payload, ...encrypted, uploaded: false }; await putCapture(capture); setCaptures(await listCaptures()); setContent(""); setTopic(""); setStatus(online ? "Saved. Encrypting and syncing…" : "Saved offline. It will sync later."); if (online) await sync(pairing); };
  const loadSnapshot = async (activePairing = pairing, showStatus = true) => { if (!activePairing || !navigator.onLine) return; setRefreshing(true); try { const response = await fetch(`${activePairing.workerUrl}/v1/inboxes/${encodeURIComponent(activePairing.inboxId)}/snapshot`, { headers: { Authorization: `Bearer ${activePairing.token}` }, cache: "no-store" }); if (!response.ok) throw new Error(`Snapshot unavailable (${response.status})`); const envelope = await response.json() as { snapshot: { iv: string; ciphertext: string; encoding: string } | null }; if (!envelope.snapshot) { if (showStatus) setStatus("Desktop has not published its memory library yet."); return; } const snapshot = await decryptSnapshot(envelope.snapshot, activePairing.key); setMemories(snapshot.memories); await setSetting("snapshot", snapshot); if (showStatus) setStatus(`${snapshot.memories.length} memories refreshed from desktop.`); } catch { if (showStatus) setStatus("Could not refresh the library. Showing the last synced copy on this phone."); } finally { setRefreshing(false); } };
  const sync = async (activePairing = pairing) => { if (!activePairing || !navigator.onLine) return; const pending = (await listCaptures()).filter((capture) => !capture.uploaded); if (pending.length) setStatus(`Syncing ${pending.length} capture${pending.length === 1 ? "" : "s"}…`); let sent = 0; for (const capture of pending) { try { const response = await fetch(`${activePairing.workerUrl}/v1/inboxes/${encodeURIComponent(activePairing.inboxId)}/captures`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${activePairing.token}` }, body: JSON.stringify({ id: capture.id, iv: capture.iv, ciphertext: capture.ciphertext, created_at: capture.created_at }) }); if (response.ok) { capture.uploaded = true; await putCapture(capture); sent += 1; } } catch { break; } } setCaptures(await listCaptures()); await loadSnapshot(activePairing, false); if (pending.length) setStatus(sent ? `${sent} encrypted capture${sent === 1 ? "" : "s"} sent to desktop inbox.` : "Sync unavailable. Your capture remains safely on this phone."); };
  const dictate = () => { const Recognition = (window as unknown as { webkitSpeechRecognition?: new () => { lang: string; interimResults: boolean; onresult: (event: { results: ArrayLike<{ 0: { transcript: string } }> }) => void; onend: () => void; start: () => void } }).webkitSpeechRecognition; if (!Recognition) { setStatus("Voice capture is not supported by this browser."); return; } const recognition = new Recognition(); recognition.lang = navigator.language; recognition.interimResults = false; recognition.onresult = (event) => setContent((current) => `${current}${current ? " " : ""}${event.results[0][0].transcript}`); recognition.onend = () => setListening(false); setListening(true); recognition.start(); };
  const filtered = memories.filter((memory) => `${memory.content} ${memory.topic ?? ""} ${memory.category ?? ""} ${memory.project ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const groups = Object.entries(filtered.reduce<Record<string, MobileMemory[]>>((result, memory) => { const label = (groupBy === "project" ? memory.project : memory.topic || memory.category)?.trim() || (groupBy === "project" ? "Inbox" : "Uncategorized"); (result[label] ??= []).push(memory); return result; }, {})).sort(([a], [b]) => a.localeCompare(b));

  return <main className="mobile-app"><header><div className="mobile-brand"><span><BrainCircuit /></span><div><strong>Recall</strong><small>Capture & browse anywhere</small></div></div><div className={`mobile-network ${online ? "online" : "offline"}`}>{online ? <Cloud /> : <CloudOff />}{online ? "Online" : "Offline"}</div></header>
    {!pairing && <section className="pair-needed"><Smartphone /><h2>Pair this phone</h2><p>Open Settings → Mobile capture on desktop Recall and scan the QR code. Your encryption key stays on your devices.</p></section>}
    <nav className="mobile-tabs"><button className={view === "capture" ? "active" : ""} onClick={() => setView("capture")}><Sparkles />Capture</button><button className={view === "memories" ? "active" : ""} onClick={() => setView("memories")}><BookOpen />Memories <b>{memories.length}</b></button></nav>
    {view === "capture" ? <><section className="quick-capture"><span className="mobile-eyebrow"><Sparkles />New memory</span><h1>What do you want to remember?</h1><div className="mobile-textarea"><textarea autoFocus value={content} onChange={(event) => setContent(event.target.value)} placeholder="An idea, decision, reminder…" /><button className={listening ? "listening" : ""} onClick={dictate}><Mic /></button></div><div className="mobile-fields"><label><Lightbulb /><input value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="Topic (automatic if blank)" /></label><label><Plus /><input value={project} onChange={(event) => setProject(event.target.value)} placeholder="Project (optional)" /></label></div><button className="mobile-save" disabled={!content.trim() || !pairing} onClick={() => void save()}><Send />Save memory</button>{status && <p className="mobile-status"><Check />{status}</p>}</section>
    <section className="mobile-recent"><div><h2>Recent captures</h2>{pairing && <button onClick={() => void sync()}><Share2 />Sync now</button>}</div>{captures.slice(0, 8).map((capture) => <article key={capture.id}><i className={capture.uploaded ? "uploaded" : "pending"} /><p>{capture.content}</p><small>{capture.uploaded ? "Encrypted inbox" : "Waiting to sync"} · {new Date(capture.created_at).toLocaleString()}</small></article>)}{!captures.length && <p className="mobile-empty">Your mobile captures will appear here.</p>}</section></> : <section className="mobile-library"><div className="mobile-library-title"><div><span className="mobile-eyebrow"><BookOpen />Local library</span><h1>Your memories</h1></div><button disabled={!pairing || refreshing} onClick={() => void loadSnapshot()}><RefreshCw className={refreshing ? "spinning" : ""} />Refresh</button></div><label className="mobile-search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search memories, topics, projects…" /></label><div className="mobile-group-toggle"><button className={groupBy === "topic" ? "active" : ""} onClick={() => setGroupBy("topic")}><Tags />Topics</button><button className={groupBy === "project" ? "active" : ""} onClick={() => setGroupBy("project")}><Folder />Projects</button></div>{status && <p className="mobile-status"><Check />{status}</p>}<div className="memory-groups">{groups.map(([label, items]) => <section key={label} className="memory-group"><header><span>{groupBy === "project" ? <Folder /> : <Tags />}{label}</span><b>{items.length}</b></header>{items.sort((a, b) => b.created_at.localeCompare(a.created_at)).map((memory) => <article key={memory.id}><p>{memory.content}</p><div>{memory.workflow_status && <span>{memory.workflow_status.replace(/_/g, " ")}</span>}{memory.priority && <span>{memory.priority}</span>}<time>{new Date(memory.created_at).toLocaleDateString()}</time></div></article>)}</section>)}{!groups.length && <p className="mobile-empty">{memories.length ? "No memories match your search." : "No desktop memories have been synced yet. Open desktop Recall and choose Sync now."}</p>}</div></section>}
    <footer><Settings />Edit memories, projects, and graphs from desktop Recall.</footer>
  </main>;
}

async function encrypt(payload: object, encodedKey: string): Promise<{ iv: string; ciphertext: string }> { const key = await crypto.subtle.importKey("raw", fromBase64url(encodedKey), "AES-GCM", false, ["encrypt"]); const iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(JSON.stringify(payload))); return { iv: toBase64url(iv), ciphertext: toBase64url(new Uint8Array(ciphertext)) }; }
async function decryptSnapshot(envelope: { iv: string; ciphertext: string; encoding: string }, encodedKey: string): Promise<MemorySnapshot> { if (envelope.encoding !== "gzip+json") throw new Error("Unsupported snapshot encoding"); const key = await crypto.subtle.importKey("raw", fromBase64url(encodedKey), "AES-GCM", false, ["decrypt"]); const decrypted = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64url(envelope.iv) }, key, fromBase64url(envelope.ciphertext)); if (!("DecompressionStream" in window)) throw new Error("This browser cannot decompress the library"); const stream = new Blob([decrypted]).stream().pipeThrough(new DecompressionStream("gzip")); const snapshot = JSON.parse(await new Response(stream).text()) as MemorySnapshot; if (snapshot.version !== 1 || !Array.isArray(snapshot.memories)) throw new Error("Invalid memory snapshot"); return snapshot; }
function fromBase64url(value: string): Uint8Array<ArrayBuffer> { const base64 = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "="); const decoded = atob(base64); const bytes = new Uint8Array(new ArrayBuffer(decoded.length)); for (let index = 0; index < decoded.length; index += 1) bytes[index] = decoded.charCodeAt(index); return bytes; }
function toBase64url(value: Uint8Array): string { let binary = ""; value.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
